name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: {
          node-version: 22,
          cache: 'npm'
          }
      - run: npm ci

      - run: npm run dist:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List dist files
        run: dir dist
      - name: Upload to R2
        shell: bash
        run: |
          aws s3 cp ./dist/latest.yml s3://clinic/ \
            --endpoint-url "${{ secrets.R2_ENDPOINT }}"
          aws s3 cp ./dist/*.exe s3://clinic/ \
            --endpoint-url "${{ secrets.R2_ENDPOINT }}"
          aws s3 cp ./dist/*.blockmap s3://clinic/ \
            --endpoint-url "${{ secrets.R2_ENDPOINT }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}